on:
  push:
    branches:
      - main

jobs:
  codeql-analysis:
    runs-on: self-hosted  # Puedes usar runners hospedados por GitHub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3  # Usar v3 en lugar de v2
        with:
          languages: javascript
          build-mode: none
            
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Backup actual
      - name: Backup current build
        run: |
          powershell -Command "
          if (Test-Path 'C:\\inetpub\\backupReact-App\\') {
            Remove-Item -Path 'C:\\inetpub\\backupReact-App\\*' -Recurse -Force;
          } else {
            New-Item -ItemType Directory -Path 'C:\\inetpub\\backupReact-App\\';
          }
          Copy-Item -Path 'C:\\inetpub\\deplyreact\\*' -Destination 'C:\\inetpub\\backupReact-App\\' -Recurse -Force;
          "

      # Instalar dependencias
      - name: Install dependencies
        run: |
          cd "C:\Users\jmsas\Documents\Proyecto practica\react-proyect"
          npm install

      # Construir la aplicación
      - name: Build React App
        run: |
          cd "C:\Users\jmsas\Documents\Proyecto practica\react-proyect"
          npm run build


      # Desplegar
      - name: Deploy to server
        run: |
          powershell -Command "
          if (Test-Path 'C:\\inetpub\\deplyreact\\') {
            Remove-Item -Path 'C:\\inetpub\\deplyreact\\*' -Recurse -Force;
          }
          Copy-Item -Path 'C:\\Users\\jmsas\\Documents\\Proyecto practica\\react-proyect\\dist\\*' -Destination 'C:\\inetpub\\deplyreact\\' -Recurse -Force;
          "

      # Rollback en caso de fallo
      - name: Rollback on failure
        if: ${{ failure() }}
        run: |
          powershell -Command "
          if (Test-Path 'C:\\inetpub\\backupReact-App\\*') {
            Remove-Item -Path 'C:\\inetpub\\deplyreact\\*' -Recurse -Force;
            Copy-Item -Path 'C:\\inetpub\\backupReact-App\\*' -Destination 'C:\\inetpub\\deplyreact\\' -Recurse -Force;
          } else {
            Write-Host 'No backup available for rollback.';
          }
          "
