name: Rollback React App

on:
  workflow_dispatch:
    inputs:
      backupId:
        description: 'ID del backup (ej: 20240522-153045)'
        required: true

jobs:
  rollback:
    runs-on: self-hosted
    
    steps:
      - name: Validar existencia del backup
        run: |
          $backupPath = "C:\inetpub\react_backups\${{ github.event.inputs.backupId }}"
          if (-not (Test-Path $backupPath)) {
              Write-Host "::error::Backup ${{ github.event.inputs.backupId }} no existe"
              exit 1
          }
        shell: powershell

      - name: Restaurar versión
        run: |
          $backupDir = "C:\inetpub\react_backups\${{ github.event.inputs.backupId }}"
          $deployPath = "C:\inetpub\deplyreact"

          # Eliminar contenido actual (con permisos elevados)
          Remove-Item -Path "$deployPath\*" -Recurse -Force -ErrorAction Stop

          # Copiar desde backup
          Copy-Item -Path "$backupDir\*" -Destination $deployPath -Recurse -Force -ErrorAction Stop

          Write-Host "Rollback exitoso a ${{ github.event.inputs.backupId }}"
        shell: powershell